// Code generated by reset tool. DO NOT EDIT.

package main

func (s *User) Reset() {
	s.ID = 0
	s.Name = ""
	s.Email = ""
	s.Active = false
	s.Tags = s.Tags[:0]
	clear(s.Settings)
	if s.Profile != nil {
		if resetter, ok := interface{}(s.Profile).(interface{ Reset() }); ok {
			resetter.Reset()
		}
		s.Profile = nil
	}
}

func (s *Profile) Reset() {
	s.Bio = ""
	s.Avatar = ""
	clear(s.SocialLinks)
	s.Metadata = s.Metadata[:0]
}

func (s *Cache) Reset() {
	clear(s.Data)
	s.Keys = s.Keys[:0]
	s.Size = 0
	s.MaxSize = 0
	s.Enabled = false
	if s.Backend != nil {
		if resetter, ok := interface{}(s.Backend).(interface{ Reset() }); ok {
			resetter.Reset()
		}
		s.Backend = nil
	}
}

func (s *Backend) Reset() {
	s.URL = ""
	s.Timeout = 0
	s.Retries = 0
	clear(s.Headers)
	s.Options = s.Options[:0]
}
