// Code generated by reset tool. DO NOT EDIT.

package testdata

func (s *TestConfig) Reset() {
	s.BaseURL = ""
	s.MaxRetries = 0
	s.Timeout = 0
	s.Enabled = false
	clear(s.Headers)
	s.Options = s.Options[:0]
	if s.Logger != nil {
		if resetter, ok := interface{}(s.Logger).(interface{ Reset() }); ok {
			resetter.Reset()
		}
		s.Logger = nil
	}
}

func (s *TestLogger) Reset() {
	s.Level = ""
	s.Format = ""
	s.Output = s.Output[:0]
}
