// Code generated by reset tool. DO NOT EDIT.

package pool

func (s *User) Reset() {
	s.ID = 0
	s.Name = ""
	s.Email = ""
	s.Active = false
	s.Tags = s.Tags[:0]
	clear(s.Settings)
	if s.Profile != nil {
		if resetter, ok := interface{}(s.Profile).(interface{ Reset() }); ok {
			resetter.Reset()
		}
		s.Profile = nil
	}
}

func (s *Profile) Reset() {
	s.Bio = ""
	s.Avatar = ""
	clear(s.SocialLinks)
	s.Metadata = s.Metadata[:0]
}
